var x_sprite;
var y_sprite;
var mytime = 0;
var mytime2 = 0;
var mycurrentime = 0;
var weight = 0;
var speed = 2;
var speedX;
var speedY;
var keyLeft;
var keyRight;
var keyUp;
var keyDown;
var keyEsc;
var keySpace;
var keyEnter;
var keyX;
var keyZ;
var huong = [];
var h;
var isAlive = true;
var realTime = 0;
var checkPlayer = true;
var player;
var itemBombs = [];
var itemShoes=[];
var countBomb=0;
var countItemSpeddGame=0;
var countkillboss=0;
var timer=0;